# Constants
OPTIONS = {'comments': False, 'reactors': True, 'progress': True, 'allow_extra_requests': False}  # True

TIMEOUT_SECS = 60

IMPORTANT_KEYS = [
    'original_request_url',
    'post_url',
    'post_id',
    'text',
    'post_text',
    'shared_text',
    'original_text',
    'time',
    'timestamp',
    'images_lowquality_description',
    'video_duration_seconds',
    'video_watches',
    'likes',
    'comments',
    'shares',
    'link',
    'user_id',
    'username',
    'user_url',
    'factcheck',
    'shared_post_id',
    'shared_time',
    'shared_user_id',
    'shared_username',
    'shared_post_url',
    'available',
    'comments_full',
    'reactors',
    'w3_fb_url',
    'reactions',
    'reaction_count',
    'page_id',
    'sharers',
]
